[server]
host = "validator4"
port = 30011
http-port = 30012
no-upnp = true
default-timeout = 5000
map-size = 1000000000
data-dir = "./validator4"
bootstrap = "rnode://7119ad2a26cdcde63dca675c4f2a4df85f404726@bootstrap?protocol=30011&discovery=40404"

[grpc-server]
host = "grpc"
port = 30015

[validators]
private-key = "c380558b21ed34779f1c29fec947353bb944d9d50c2338b899d6e2faed8849fa"
