[server]
host = "validator3"
port = 30011
http-port = 30012
no-upnp = true
default-timeout = 1000
map-size = 1000000000
data-dir = "./validator3"
bootstrap = "rnode://7119ad2a26cdcde63dca675c4f2a4df85f404726@bootstrap:30011"

[grpc-server]
host = "grpc"
port = 30015

[validators]
private-key = "7d8e4576b131492bdb442f510ab76a506cdcf5e610a69dc1163a674f47a80448"
